import { config } from "dotenv";

config();

const PORT = process.env.PORT;
const GMAIL_ID = process.env.GMAIL_ID;
const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID;
const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET;
const GOOGLE_REFRESH_TOKEN = process.env.GOOGLE_REFRESH_TOKEN;
const DATABASE_URL = process.env.DATABASE_URL;
const JWT_SECRET = process.env.JWT_SECRET;
const GOOGLE_CLIENT_CALLBACKURL = process.env.GOOGLE_CLIENT_CALLBACKURL;
const GOOGLE_ANDROID_CLIENT_ID = process.env.GOOGLE_ANDROID_CLIENT_ID;
const GOOGLE_IOS_CLIENT_ID = process.env.GOOGLE_IOS_CLIENT_ID;

if (
  !PORT ||
  !GMAIL_ID ||
  !GOOGLE_REFRESH_TOKEN ||
  !GOOGLE_CLIENT_ID ||
  !GOOGLE_CLIENT_SECRET ||
  !GOOGLE_CLIENT_CALLBACKURL ||
  !DATABASE_URL ||
  !JWT_SECRET ||
  !GOOGLE_ANDROID_CLIENT_ID ||
  !GOOGLE_IOS_CLIENT_ID
) {
  throw Error("Something is not defined in environment variables");
}

const envConfig = {
  PORT: PORT,
  GMAIL_ID: GMAIL_ID,
  GOOGLE_REFRESH_TOKEN: GOOGLE_REFRESH_TOKEN,
  GOOGLE_CLIENT_ID: GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: GOOGLE_CLIENT_SECRET,
  GOOGLE_CLIENT_CALLBACKURL: GOOGLE_CLIENT_CALLBACKURL,
  DATABASE_URL: DATABASE_URL,
  JWT_SECRET: JWT_SECRET,
  GOOGLE_ANDROID_CLIENT_ID: GOOGLE_ANDROID_CLIENT_ID,
  GOOGLE_IOS_CLIENT_ID: GOOGLE_IOS_CLIENT_ID,
};

export default envConfig;
